### ISSUE TITLE
 【開発環境】mysqlをインストールして、DBを作成する

### ISSUE THREAD

**Issue by arith-alexander** [arith-alexander/opinion#13]
DB名 opinion
サーバー 35.163.61.229

**Comment by arith-alexander** [comment]
@arith-k-saito 
着手します

**Comment by arith-alexander** [comment]
3306ポートを開きました

**Comment by arith-alexander** [comment]
<img width="534" alt="2016-11-11 14 42 44" src="https://cloud.githubusercontent.com/assets/15188185/20205550/24106ce8-a81d-11e6-9814-4cc8981e880a.png">

**Comment by arith-alexander** [comment]
@arith-k-saito 
パスワードはチャットで送ります

**Comment by arith-alexander** [comment]
完了しましたのでクローズ

**Comment by arith-k-saito** [comment]
アクセス確認しました。
