### ISSUE TITLE
【開発環境】ハレルさんIDEを構築する

### ISSUE THREAD

**Issue by arith-Harrell** [arith-alexander/opinion#18]
関連issue #8  ?

**Comment by arith-alexander** [comment]
<img width="774" alt="2016-11-11 16 00 06" src="https://cloud.githubusercontent.com/assets/15188185/20207049/fd9222c2-a827-11e6-9bc2-7d523a861ac4.png">
<img width="560" alt="2016-11-11 16 00 12" src="https://cloud.githubusercontent.com/assets/15188185/20207050/fd933e46-a827-11e6-83f7-1bec25444466.png">

**Comment by arith-alexander** [comment]
document root path /www/harrell

**Comment by arith-Harrell** [comment]
@arith-k-saito  @arith-alexander 
着手いたします。

**Comment by arith-k-saito** [comment]
終わっているようなのでcloseします。
