### ISSUE TITLE
【アンケート】質問の内容を編集しやすくするために、DBに保存してDBから読むように対応する

### ISSUE THREAD

**Issue by arith-alexander** [arith-alexander/opinion#19]
前提issue https://github.com/arith-alexander/opinion/issues/16
対象テーブル question

**Comment by arith-alexander** [comment]
@arith-k-saito @arith-Harrell 
着手します。

**Comment by arith-k-saito** [comment]
https://github.com/arith-alexander/opinion/pull/20
で対応済み
