### ISSUE TITLE
【アンケート】選択肢の内容を編集しやすくするために、DBに保存してDBから読むように対応する 

### ISSUE THREAD

**Issue by arith-alexander** [arith-alexander/opinion#26]
https://github.com/arith-alexander/opinion/issues/19 を参考にする
対象テーブル choice

**Comment by arith-alexander** [comment]
@arith-Harrell @arith-k-saito 
着手します

**Comment by arith-k-saito** [comment]
https://github.com/arith-alexander/opinion/pull/29
にて対応済み
