### ISSUE TITLE
【開発環境】インスタンスにバーチャルホストの設定をする

### ISSUE THREAD

**Issue by arith-k-saito** [arith-alexander/opinion#4]

**Comment by arith-alexander** [comment]
@arith-k-saito 
斉藤さん用、サーシャ用、二つのバーチャルホスト。
ポートで分ける。

**Comment by arith-alexander** [comment]
@arith-k-saito 
作成しました

サーシャ
http://35.163.61.229:81/
ホームディレクトリ /www/alex

齊藤さん
http://35.163.61.229:82/
ホームディレクトリ /www/saito

**Comment by arith-alexander** [comment]
@arith-k-saito 
コスト３０分
