### ISSUE TITLE
【アンケート】アンケート機能を実装する

### ISSUE THREAD

**Issue by arith-k-saito** [arith-alexander/opinion#6]
アンケート機能を実装するepic

**Comment by arith-k-saito** [comment]
最初の時点ではやらないで後回しにすること：
- css等使ったページのデザイン
- データベースの使用
- 質問内容の編集(最初はhtmlに直書き
- 管理画面での保存データの閲覧
- 開発環境以外に本番環境の整備(時間的に今回はやらない

**Comment by arith-alexander** [comment]
完了です。
クローズします。
